import "@/styles/globals.css";

import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import { AppSidebar } from "@/components/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { TRPCReactProvider } from "@/trpc/react";
import MySidebarProvider from "@/components/SidebarProvider";
import { getSession } from "@/server/better-auth/server";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  const session = await getSession();
  console.log(session);
  return (
    <html className={`${jakarta.variable}`} lang="en">
      <body>
        <TRPCReactProvider>
          <SidebarProvider>
            {!session ? null : <AppSidebar /> }
            <main className="flex-1">{children}</main>
          </SidebarProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
